name: vector_tracker_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  supabase_flutter: ^2.5.3
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  uuid: ^4.3.3
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.6.0
  get_it: ^7.6.7
  logger: ^2.3.0
  google_maps_cluster_manager_2: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
